In [73]:
import torch
torch.manual_seed(42)

In [74]:
x = torch.rand(5, dtype=torch.float32)
print(x, x.dtype)

tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904]) torch.float32


In [75]:
r_min = x.min()
r_max = x.max()
print(r_min, r_max)

q_min = torch.iinfo(torch.int8).min
q_max = torch.iinfo(torch.int8).max
print(q_min, q_max)

tensor(0.3829) tensor(0.9593)
-128 127


In [76]:
s = (r_max-r_min)/(q_max - q_min)
z = (q_min - r_min/s)

In [77]:
y = torch.round(x/s + z).to(torch.int8)
print(y)

tensor([  93,  107, -128,  127, -125], dtype=torch.int8)


In [78]:
x_r = (y.to(torch.float32) - z)*s
print(x_r)

tensor([0.8824, 0.9141, 0.3829, 0.9593, 0.3896])


In [79]:
torch.abs(x - x_r)

tensor([1.7750e-04, 9.0939e-04, 5.9605e-08, 5.9605e-08, 8.0273e-04])